apiVersion: "giantswarm.io/v1"
kind: Certificate
metadata:
  name: "{{.Values.clusterName}}-api"
  namespace: "default"
  labels:
    clusterID: "{{.Values.clusterName}}"
    clusterComponent: "api"
spec:
  clusterID: "{{.Values.clusterName}}"
  clusterComponent: "api"
  commonName: "api.{{.Values.clusterName}}.{{.Values.commonDomain}}"
  altNames:
  - "{{.Values.clusterName}}.{{.Values.commonDomain}}"
  - "k8s-master-vm"
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.cluster.local"
  ipSans:
  - "172.31.0.1"
  ttl: "720h"
  allowBareDomains: true
