apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: cert-operator-local
    namespace: default
    labels:
      app: cert-operator-local
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cert-operator-local
    spec:
      volumes:
      containers:
      - name: cert-operator
        image: quay.io/giantswarm/cert-operator:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --service.vault.config.address=http://{{.Values.vaultHost}}:8200
        - --service.vault.config.token={{.Values.vaultToken}}
        - --service.vault.config.pki.ca.ttl=1440h
        - --service.vault.config.pki.commonname.format=%s.{{.Values.commonDomain}}
        - --service.kubernetes.incluster=true
        - --service.resource.vaultcrt.expirationthreshold=24h
        - --service.resource.vaultcrt.namespace=default
