apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:0.7.3
          ports:
          - name: http
            containerPort: 8200
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          args:
          - server
          - -dev
          - -dev-root-token-id={{.Values.vaultToken}}
          - -log-level=debug

---

apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  type: NodePort
  ports:
    - name: api
      port: 8200
      targetPort: http
  selector:
    app: vault
  sessionAffinity: None
