version: 2.1

orbs:
  architect: giantswarm/architect@0.8.4

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - build

      - architect/push-to-docker-legacy:
          name: push-cert-operator-to-quay
          image: "quay.io/giantswarm/cert-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build

      - hold-push-cert-operator-to-aliyun-pr:
          type: approval
          requires:
            - build
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker-legacy:
          name: push-cert-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-cert-operator-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-cert-operator-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - deploy:
          name: deploy
          requires:
            - push-cert-operator-to-aliyun-master
            - push-cert-operator-to-quay
          filters:
            branches:
              only: master
