version: 2.1

orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: cert-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-cert-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cert-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-operator-to-aws-app-collection
          app_name: "cert-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cert-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-operator-to-azure-app-collection
          app_name: "cert-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-cert-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
