apiVersion: "giantswarm.io/v1"
kind: Certificate
metadata:
  name: "example-cluster-calico"
  namespace: "default"
spec:
  clusterID: "example-cluster"
  clusterComponent: "calico"
  commonName: "calico.example-cluster.aws.giantswarm.io"
  altNames:
  ipSans:
  ttl: "720h"
  allowBareDomains: false
