apiVersion: "giantswarm.io/v1"
kind: Certificate
metadata:
  name: "example-cluster-etcd"
  namespace: "default"
  labels:
    clusterID: "example-cluster"
    clusterComponent: "etcd"
spec:
  clusterID: "example-cluster"
  clusterComponent: "etcd"
  commonName: "etcd.example-cluster.aws.giantswarm.io"
  altNames:
  ipSans:
  ttl: "720h"
  allowBareDomains: false
