apiVersion: "giantswarm.io/v1"
kind: Certificate
metadata:
  name: "example-cluster-service-account"
  namespace: "default"
  labels:
    clusterID: "example-cluster"
    clusterComponent: "service-account"
spec:
  clusterID: "example-cluster"
  clusterComponent: "service-account"
  commonName: "service-account.example-cluster.aws.giantswarm.io"
  altNames:
  ipSans:
  ttl: "720h"
  allowBareDomains: false
