apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-operator-configmap
  namespace: giantswarm
data:
  config.yml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      vault:
        config:
          address: '{{ .Installation.V1.Auth.Vault.Address | urlString }}'
          certificate:
            allowedDomainsFormat: '%s.{{ .Values.Installation.V1.Guest.Kubernetes.API.EndpointBase }},kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster.local'
          pki:
            ca:
              ttl: '{{ .Installation.V1.Auth.Vault.CA.TTL | shortDuration }}'
            commonname:
              format: '%s.{{ .Installation.V1.Guest.Kubernetes.API.EndpointBase }}'
