project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  tag: "[[ .Version ]]"
userID: 1000
groupID: 1000

crd:
  labelSelector: ""

k8sJwtToVaultTokenImage:
  name: giantswarm/k8s-jwt-to-vault-token
  tag: 0.1.0

registry:
  domain: docker.io

resource:
  expirationThreshold: "2160h"

vault:
  address: ""
  ca:
    ttl: "87600h"

workloadCluster:
  kubernetes:
    api:
      endpointBase: ""
