project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  tag: "[[ .Version ]]"
userID: 1000
groupID: 1000

crd:
  labelSelector: ""

k8sJwtToVaultTokenImage:
  name: giantswarm/k8s-jwt-to-vault-token
  tag: 0.1.0

registry:
  domain: docker.io

resource:
  expirationThreshold: "2160h"

vault:
  address: ""
  ca:
    ttl: "87600h"

workloadCluster:
  kubernetes:
    api:
      endpointBase: ""

provider:
  kind: "aws"

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  default:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
  initContainers:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

global:
  podSecurityStandards:
    enforced: false
