clusterRoleBindingName: cert-operator
clusterRoleBindingNamePSP: cert-operator-psp
clusterRoleName: cert-operator
clusterRoleNamePSP: cert-operator-psp
namespace: giantswarm
pspName: cert-operator-psp

userID: 1000
groupID: 1000

Installation:
  V1:
    Registry:
      Domain: quay.io
