apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      crd:
        labelSelector: '{{ .Values.crd.labelSelector }}'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      resource:
        vaultCrt:
          expirationThreshold: '{{ .Values.resource.expirationThreshold }}'
          namespace: 'default'
      vault:
        config:
          address: '{{ .Values.vault.address }}'
          pki:
            ca:
              ttl: '{{ .Values.vault.ca.ttl }}'
            commonname:
              format: '%s.{{ .Values.workloadCluster.kubernetes.api.endpointBase }}'
