apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.selector" . | nindent 8 }}
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
    spec:
      volumes:
      - name: {{ include "name" . }}-configmap
        configMap:
          name: {{ include "resource.default.name" . }}
          items:
            - key: config.yaml
              path: config.yaml
      - name: {{ include "name" . }}-secret
        secret:
          secretName: {{ include "resource.default.name" . }}
          items:
            - key: secret.yaml
              path: secret.yaml
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs/
      serviceAccountName: {{ include "resource.default.name" . }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      initContainers:
      - args:
        - --vault-address={{ .Values.Installation.V1.Auth.Vault.Address }}
        - --vault-role=cert-operator
        - --vault-token-secret-name={{ include "resource.default.name" . }}-vault-token
        - --vault-token-secret-namespace={{ include "resource.default.namespace" . }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.k8sJwtToVaultToken.name}}:{{ .Values.k8sJwtToVaultToken.tag }}"
        imagePullPolicy: Always
        name: ensure-vault-token
      containers:
      - name: cert-operator
        image: "{{ .Values.Installation.V1.Registry.Domain }}/giantswarm/cert-operator:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ include "name" . }}-configmap
          mountPath: /var/run/cert-operator/configmap/
        - name: {{ include "name" . }}-secret
          mountPath: /var/run/cert-operator/secret/
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificate.crt
        - name: ssl-certs
          mountPath: /etc/ssl/certs/
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/cert-operator/configmap/
        - --config.dirs=/var/run/cert-operator/secret/
        - --config.files=config
        - --config.files=secret
        - --service.vault.token=$(VAULT_TOKEN)
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: {{ include "resource.default.name" . }}-vault-token
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
