apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "cert-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-operator.selectorLabels" . | nindent 8 }}
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      volumes:
      - name: cert-operator-configmap
        configMap:
          name: {{ .Chart.Name }}
          items:
            - key: config.yaml
              path: config.yaml
      - name: cert-operator-secret
        secret:
          secretName: {{ .Chart.Name }}
          items:
            - key: secret.yaml
              path: secret.yaml
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs/
      serviceAccountName: cert-operator
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: cert-operator
        image: "{{ .Values.Installation.V1.Registry.Domain }}/giantswarm/cert-operator:[[ .SHA ]]"
        volumeMounts:
        - name: {{ .Chart.Name }}-configmap
          mountPath: /var/run/{{ .Chart.Name }}/configmap/
        - name: {{ .Chart.Name }}-secret
          mountPath: /var/run/{{ .Chart.Name }}/secret/
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificate.crt
        - name: ssl-certs
          mountPath: /etc/ssl/certs/
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Chart.Name }}/configmap/
        - --config.dirs=/var/run/{{ .Chart.Name }}/secret/
        - --config.files=config
        - --config.files=secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
