apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - certconfigs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
    verbs:
      - get
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - awsconfigs
      - azureconfigs
      - kvmconfigs
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cert-operator-configmap
    verbs:
      - get
  - nonResourceURLs:
      - "/"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ tpl .Values.resource.psp.name . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.psp.name . }}
  apiGroup: rbac.authorization.k8s.io
