apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "cert-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret.yaml: |-
    service:
      vault:
        config:
          token: {{ .Values.Installation.V1.Secret.CertOperator.Service.Vault.Config.Token }}
