apiVersion: v1
kind: Secret
metadata:
  name: cert-operator-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  secret.yaml: |-
    service:
      vault:
        config:
          token: {{ .Values.Installation.V1.Secret.CertOperator.Service.Vault.Config.Token }}
