apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  secret.yaml: |-
    service:
      vault:
        config:
          token: {{ .Values.Installation.V1.Secret.CertOperator.Service.Vault.Config.Token }}
