apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-operator-configmap
  namespace: giantswarm
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      resource:
        vaultCrt:
          expirationThreshold: '24h'
          namespace: 'default'
      vault:
        config:
          address: '{{ .Values.Installation.V1.Auth.Vault.Address }}'
          pki:
            ca:
              ttl: '{{ .Values.Installation.V1.Auth.Vault.CA.TTL }}'
            commonname:
              format: '%s.{{ .Values.Installation.V1.Guest.Kubernetes.API.EndpointBase }}'
