apiVersion: v1
kind: Secret
metadata:
  name: cert-operator-secret
  namespace: giantswarm
type: Opaque
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.CertOperator.SecretYaml | b64enc | quote }}
